#################################################################################################################
# The deployment for the application
#################################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: cpolydorou/requestinformation:20230213
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: "800m"
            memory: "512Mi"      
          limits:
            cpu: "800m"
            memory: "512Mi"